# DATABASE
IMG_SHAPE = 28 #ipotizing squared shape images 28
BLOCK_SHAPE = 4
CLASSES = 8 #8
THRESHOLD = 128 #128

# SPIKING NEURAL P SYSTEM
NEURONS_LAYER1 = int(IMG_SHAPE ** 2) #784
NEURONS_LAYER2 = int((IMG_SHAPE / BLOCK_SHAPE) ** 2) #49
NEURONS_LAYER1_2 = int(NEURONS_LAYER1 + NEURONS_LAYER2) #833
NEURONS_TOTAL = NEURONS_LAYER1_2 + CLASSES # 841

# PARAMETER TUNING
TRAIN_SIZE = 5000
TEST_SIZE = 1000
PRUNING_PERC = 0.5
POSITIVE_REINFORCE = CLASSES - 1
NEGATIVE_PENALIZATION = 1

# STRING
CSV_NAME = "neurons784image.csv"
CSV_NAME_PRUNED = "neurons784image_pruned.csv"
INPUT_TYPE = "image_spike_train"

